### ISSUE TITLE
THIS PROBLEM OCCOURS

### ISSUE THREAD

**Issue by Khattak24** [nttcom/jumbotron#16]
Mixed Content: The page at 'https://jageerx.com/' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Noto+Serif:400,400italic,700|Open+Sans:400,600,700'. This request has been blocked; the content must be served over HTTPS.

**Comment by rotsuya** [comment]
Do you use jumbotron at  https://jageerx.com/ ? I couldn't find it.
